version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    ports:
      - "5000:5000"
    
    depends_on:
      - db

  db:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=store_locator
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
